version: '2'
services:
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.107
      KAFKA_CREATE_TOPICS: "topic1:1:2,topic2:1:2"
      KAFKA_ZOOKEEPER_CONNECT: "192.168.99.105:2181,192.168.99.105:2182,192.168.99.105:2183"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
